import java.util.Scanner;

public class J1 {

	public static void main(String[] args) {
		Scanner in = new Scanner(System.in);
		int n = in.nextInt();

		switch (n) {
			case 0: System.out.println(" * * *");
					System.out.println("*     *");
					System.out.println("*     *");
					System.out.println("*     *");
					System.out.println();
					System.out.println("*     *");
					System.out.println("*     *");
					System.out.println("*     *");
					System.out.println(" * * *");
					break;
			case 1: System.out.println();
					System.out.println("      *");
					System.out.println("      *");
					System.out.println("      *");
					System.out.println();
					System.out.println("      *");
					System.out.println("      *");
					System.out.println("      *");
					System.out.println();
					break;
			case 2: System.out.println(" * * *");
					System.out.println("      *");
					System.out.println("      *");
					System.out.println("      *");
					System.out.println(" * * *");
					System.out.println("*");
					System.out.println("*");
					System.out.println("*");
					System.out.println(" * * *");
					break;
			case 3: System.out.println(" * * *");
					System.out.println("      *");
					System.out.println("      *");
					System.out.println("      *");
					System.out.println(" * * *");
					System.out.println("      *");
					System.out.println("      *");
					System.out.println("      *");
					System.out.println(" * * *");
					break;
			case 4: System.out.println();
					System.out.println("*     *");
					System.out.println("*     *");
					System.out.println("*     *");
					System.out.println(" * * *");
					System.out.println("      *");
					System.out.println("      *");
					System.out.println("      *");
					System.out.println();
					break;
			case 5: System.out.println(" * * *");
				    System.out.println("*");
				    System.out.println("*");
				    System.out.println("*");
					System.out.println(" * * *");
					System.out.println("      *");
					System.out.println("      *");
					System.out.println("      *");
					System.out.println(" * * *");
					break;
			case 6: System.out.println(" * * *");
					System.out.println("*");
					System.out.println("*");
					System.out.println("*");
					System.out.println(" * * *");
					System.out.println("*     *");
					System.out.println("*     *");
					System.out.println("*     *");
					System.out.println(" * * *");
					break;
			case 7: System.out.println(" * * *");
					System.out.println("      *");
					System.out.println("      *");
					System.out.println("      *");
					System.out.println();
					System.out.println("      *");
					System.out.println("      *");
					System.out.println("      *");
					System.out.println();
					break;
			case 8: System.out.println(" * * *");
					System.out.println("*     *");
					System.out.println("*     *");
					System.out.println("*     *");
					System.out.println(" * * *");
					System.out.println("*     *");
					System.out.println("*     *");
					System.out.println("*     *");
					System.out.println(" * * *");
					break;
			case 9: System.out.println(" * * *");
					System.out.println("*     *");
					System.out.println("*     *");
					System.out.println("*     *");
					System.out.println(" * * *");
					System.out.println("      *");
					System.out.println("      *");
					System.out.println("      *");
					System.out.println(" * * *");
					break;
		}
	}

}
